/*
AUTHOR: Nicholas Arroyo
DATE:	November 23, 2015
CLASS:	CPSC362
DESCRIPTION: 
		Patient data object. Holds important information we need to keep track of the patient, as well as 
		methods to retrieve said information without exposing the variables themselves.
		Information will be filled out upon the object's creation via the constructor.

		For example, in the main class, when the secretary takes in the information,
		it will be saved in something like "FirstName, LastName, Address, etc." variables, respectively.
		Then, after all the important information is gained, the object will be created like this:
		"Patient PatientName = new Patient(FirstName, LastName, Address, ...)"

		NOTE: we could have the PatientID be passed in too, which could be a value generated by
		the main program, and passed in and saved to this object as well.

		Implementations will be done in Patient.cpp.

*/

#pragma once

class Patient
{
	public:
		bool inUse;
		
		Patient(const char *, const char *, long long, int, int);
		Patient();

		Patient & setFirstName(const char *);
		Patient & setLastName(const char *);

		const char * returnFirstName();
		const char * returnLastName();
		long long returnPhone();
		int returnPrefContact();
		int returnID();
	private:
		char FirstName[20];				//First Name of patient
		char LastName[20];				//Last Name of patient
		long long Phone;				//integer representation of patient's Phone number
		int PreferredContact;				//0 = prefers email contact, 1 = prefers text message contact
		int PatientID;						//Unique ID identifying this patient
};